const categoriesTypes = {
    GET_DATA: "GET_DATA",
    GET_DATA_BY_NAME: "GET_DATA_BY_NAME",
    SORT_BY_RATING_HIGH_TO_LOW: "SORT_BY_RATING_HIGH_TO_LOW",
    SORT_BY_RATING_LOW_TO_HIGH: "SORT_BY_RATING_LOW_TO_HIGH",
    SORT_BY_NAME_A_Z: "SORT_BY_NAME_A_Z",
    SORT_BY_NAME_Z_A: "SORT_BY_NAME_Z_A",
    SORT_BY_PRICE_HIGH_TO_LOW: "SORT_BY_PRICE_HIGH_TO_LOW",
    SORT_BY_PRICE_LOW_TO_HIGH: "SORT_BY_PRICE_LOW_TO_HIGH"
}

export default categoriesTypes;